feat: Move InputMask to TypeScript
mbank-design/react-input-mask pull request #1
Opened 2022-11-23 02:15 UTC by tymzar

2022-11-24 13:30 UTC, antoni commented
Ad. commit message. Co powiesz na: 
`feat: Convert project to TypeScript`

2022-11-24 20:17 UTC, antoni requested changes
Dobrze byloby przepuscic projekt przez nasz konfig ESLinta i zobaczyc, w ktorych miejscach ESLint powie, ze trzeba otypowac funkcje/zmienne. Wydaje mi sie, ze teraz w paru miejscach brakuje otypowania

2022-11-24 20:17 UTC, antoni commented on demo/package.json
> +    "react": "^18.2.0",
Skasowałbym `^`, bo według mnie to zła praktyka

2022-11-24 20:17 UTC, antoni commented on src/InputMask.hooks.tsx
> +export function usePrevious<T>(value: T): T {
Uzylbym tu jakiejs nazwy typu generycznego, ktora wskazywalaby na to co sie pod tym typem kryje

2022-11-24 20:17 UTC, antoni commented on src/InputMask.hooks.tsx
> +function setRef<T>(
Uzylbym tu jakiejs nazwy typu generycznego, ktora wskazywalaby na to co sie pod tym typem kryje

2022-11-24 20:17 UTC, antoni commented on src/InputMask.tsx
> +    { alwaysShowMask = false, maskPlaceholder = '_', ...props }: InputMaskProps,
To uwaga nie do tego PR, ale na przyszlosc - nie jestem przekonany, ze tu powinien byc defaultowy placeholder (`_`). Moze w ogole nie powinno byc defaulta

2022-11-24 20:17 UTC, antoni commented on src/children-wrapper.tsx
> +export function InputMaskChildrenWrapper(props: any) {
Nie jestesmy w stanie okreslic typu lepiej niz `any`?

2022-11-24 20:17 UTC, antoni commented on src/InputMask.hooks.tsx
> +export function useCombinedRef<T>(
Uzylbym tu jakiejs nazwy typu generycznego, ktora wskazywalaby na to co sie pod tym typem kryje

2022-11-24 20:17 UTC, antoni commented on src/utils/helpers.ts
> +export function findLastIndex<T>(
Uzylbym tu jakiejs nazwy typu generycznego, ktora wskazywalaby na to co sie pod tym typem kryje

2022-11-24 20:17 UTC, antoni commented on src/utils/helpers.ts
> +export function toString<T>(value: T): string {
Nie rozumiem tej funkcji, dlaczego nie uzyjemy po prostu `Object.toString()`?

2022-11-24 20:17 UTC, antoni commented on src/utils/helpers.ts
> +export function repeat(repeatString: string, n = 1) {
https://caniuse.com/mdn-javascript_builtins_string_repeat ?

Tylko trzeba obsluzyc przypadek, w ktorym obecnie korzystamy z defaultowego `n`

2022-11-24 20:17 UTC, antoni commented on src/utils/helpers.ts
> +export function findLastIndex<T>(
Inna sprawa, czemu nie https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLastIndex ?

Jezeli chodzi o kompatybilnosc z jakimis starszymi przegladarkami, to interesuja nas tylko przegladarki wspierane przez DS

2022-11-25 13:08 UTC, tymzar commented on CHANGELOG.md
> +# Changelog
To usuwam c;

2022-11-25 13:25 UTC, tymzar commented on src/InputMask.tsx
> +    { alwaysShowMask = false, maskPlaceholder = '_', ...props }: InputMaskProps,
spoko, jakby może nie powinno jej być, ale zostawiłbym ją na wypadek jakbyśmy chcieli kiedyś wypuścić to publicznie, to wtedy nie będzie problemów z przejściem na naszą bibliotekę

2022-11-25 14:33 UTC, tymzar commented on src/utils/helpers.ts
> +export function toString<T>(value: T): string {
Wykorzystana w jednym miejscu, usuwam

2022-11-25 15:13 UTC, tymzar commented on src/utils/helpers.ts
> +export function repeat(repeatString: string, n = 1) {
tutaj wykorzystujemy ją sposób bo jest ona tylko przekazywana do reduce'a

2022-11-25 15:24 UTC, tymzar commented on src/children-wrapper.tsx
> +export function InputMaskChildrenWrapper(props: any) {
Jesteśmy c;

2022-11-25 18:34 UTC, merged